const assert=require('assert');global.window=global;global.imageSafety=require('../src/utils/imageSafety.js');global.JiaQuotaManager=require('../src/services/quotaManager.js');const enrichment=require('../src/services/enrichment.js');
(async()=>{
  assert.deepStrictEqual(enrichment.detectMissingFields({photos:['https://example.com/a.jpg'],address:'A',phone:'1',website:'https://x',openingHours:'Mo-Fr',priceLevel:2}),[],'detectMissingFields complete');
  assert(global.imageSafety.isBlockedLegacyGoogleImage('https://maps.googleapis.com/maps/api/place/photo?photo_reference=x'),'blocked Google image');
  assert(!global.imageSafety.isBlockedLegacyGoogleImage('https://lh3.googleusercontent.com/d/user-upload'),'user Drive image remains allowed');
  const memory=new Map();global.JiaQuotaManager.configure({get:async id=>memory.get(id)||{used:0},set:async(id,v)=>memory.set(id,v)});assert(await global.JiaQuotaManager.canConsume('foursquare'),'quota canConsume');memory.set(global.JiaQuotaManager.documentId('foursquare'),{used:450});assert.strictEqual(await global.JiaQuotaManager.canConsume('foursquare'),false,'quota hard stop');memory.clear();
  global.JIA_ENRICHMENT_PROXY_URL='';const here=require('../src/providers/hereAdapter.js');assert.strictEqual((await here.search({name:'x'})).status,'disabled_no_proxy','disabled_no_key/proxy safe skip');
  const calls=[];global.JiaProviderAdapters={nominatim:{search:async()=>{calls.push('nominatim');return null;}},overpass:{search:async()=>{calls.push('overpass');return{provider:'overpass',sourceId:'n1',address:'Recovered'}}},foursquare:{search:async()=>{calls.push('foursquare');return null;}},here:{search:async()=>null},geoapify:{search:async()=>null}};let saved=null;enrichment.configure({save:async p=>saved=p});const base={jiaPlaceId:'jia_1',name:'Test',location:{lat:22,lng:120},photos:['https://example.com/a.jpg'],phone:'1',website:'https://x',openingHours:'x',priceLevel:1};const result=await enrichment.enrichPlace(base,{force:true});assert.deepStrictEqual(calls,['nominatim','overpass'],'provider fallback');assert.strictEqual(result.place.address,'Recovered');assert(saved,'writeback');
  assert(enrichment.isCoolingDown({...base,enrichment:{lastCheckedAt:new Date().toISOString()}}),'cooldown');const merged=enrichment.mergeOnlyMissing({...base,address:'Keep'},{provider:'overpass',address:'Replace',phone:'2'},['address','phone']);assert.strictEqual(merged.address,'Keep');assert.strictEqual(merged.phone,'1','merge only missing fields');
  console.log(JSON.stringify({tests:8,status:'passed'}));
})().catch(error=>{console.error(error);process.exitCode=1;});
