(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.JiaEnrichment=api;})(typeof window!=='undefined'?window:null,function(root){
  'use strict';
  const COOLDOWN_MS=24*60*60*1000,ORDER=['nominatim','overpass','foursquare','here','geoapify'];let storage=null;
  const present=v=>Array.isArray(v)?v.length>0:v!==null&&v!==undefined&&String(v).trim()!=='';
  function safePhotos(place){const safety=root?.imageSafety||{filterSafeImages:x=>x||[]};return safety.filterSafeImages([...(place?.photos||[]),...(place?.legacyRestaurantPhotos||[]),...(place?.communityPhotos||[]),...(place?.externalPhotos||[])]);}
  function detectMissingFields(place){const missing=[];if(!safePhotos(place).length)missing.push('photo');if(!present(place?.address))missing.push('address');if(!present(place?.phone))missing.push('phone');if(!present(place?.website))missing.push('website');if(!present(place?.openingHours))missing.push('openingHours');if(!present(place?.priceLevel)&&!present(place?.communityStats?.averageSpend))missing.push('price');return missing;}
  function lastCheckedMs(place){const value=place?.enrichment?.lastCheckedAt;if(!value)return 0;if(typeof value==='string')return new Date(value).getTime()||0;if(typeof value?.toMillis==='function')return value.toMillis();if(value.seconds)return value.seconds*1000;return 0;}
  function isCoolingDown(place,now=Date.now()){return now-lastCheckedMs(place)<COOLDOWN_MS;}
  function mergeOnlyMissing(place,data,requested){const next=JSON.parse(JSON.stringify(place||{})),fields=new Set(requested||detectMissingFields(next));if(fields.has('address')&&!present(next.address)&&present(data?.address))next.address=data.address;if(fields.has('phone')&&!present(next.phone)&&present(data?.phone))next.phone=data.phone;if(fields.has('website')&&!present(next.website)&&present(data?.website))next.website=data.website;if(fields.has('openingHours')&&!present(next.openingHours)&&present(data?.openingHours))next.openingHours=data.openingHours;if(fields.has('price')&&!present(next.priceLevel)&&present(data?.priceLevel))next.priceLevel=data.priceLevel;if(fields.has('photo')&&data?.externalPhotos?.length){const safety=root?.imageSafety||{filterSafeImages:x=>x||[]};next.externalPhotos=[...new Set([...(next.externalPhotos||[]),...safety.filterSafeImages(data.externalPhotos)])];}if(Number.isFinite(data?.rating)){next.externalRatings={...(next.externalRatings||{}),[data.provider]:{value:data.rating,count:data.ratingCount||null,updatedAt:new Date().toISOString()}};}next.sourceIds={...(next.sourceIds||{}),...(data?.sourceId&&data?.provider?{[data.provider]:data.sourceId}:{})};return next;}
  async function enrichPlace(place,options={}){if(!place?.jiaPlaceId)return {place,status:'invalid_place',providers:[]};const before=detectMissingFields(place);if(!before.length)return {place,status:'complete',providers:[]};if(!options.force&&isCoolingDown(place))return {place,status:'cooldown',providers:[]};let next=JSON.parse(JSON.stringify(place)),attempts=[];
    for(const provider of ORDER){const needed=detectMissingFields(next);if(!needed.length)break;const adapter=root?.JiaProviderAdapters?.[provider];if(!adapter){attempts.push({provider,status:'adapter_missing'});continue;}if(root?.JiaQuotaManager&&!(await root.JiaQuotaManager.canConsume(provider))){attempts.push({provider,status:'quota_stop'});continue;}let data;try{data=await adapter.search(next,needed);}catch(error){attempts.push({provider,status:'error',message:String(error.message||error)});continue;}if(!data||(data.status&&data.status!=='success'&&data.status!=='matched')){attempts.push({provider,status:data?.status||'no_match'});continue;}if(root?.JiaQuotaManager)await root.JiaQuotaManager.consume(provider);const previous=detectMissingFields(next);next=mergeOnlyMissing(next,data,previous);attempts.push({provider,status:'matched',recovered:previous.filter(field=>!detectMissingFields(next).includes(field)),match:data.match||null});}
    next.enrichment={...(next.enrichment||{}),lastCheckedAt:new Date().toISOString(),missingFields:detectMissingFields(next),attempts:attempts.map(x=>({provider:x.provider,status:x.status})),version:1};if(storage?.save)await storage.save(next);return {place:next,status:'checked',providers:attempts,before,after:detectMissingFields(next)};
  }
  function aggregateCommunity(rows){const ratingValues=[],spends=[],photos=[];for(const row of rows||[]){const rating=Number(row.ratingValue??row.ratingNumeric);if(Number.isFinite(rating)&&rating>0)ratingValues.push(rating);const spend=Number(row.spend??row.perPersonSpend);if(Number.isInteger(spend)&&spend>=1&&spend<=100000)spends.push(spend);for(const p of [...(row.photos||[]),row.photoUrl].filter(Boolean))photos.push(p);}const safe=(root?.imageSafety?.filterSafeImages||((x)=>x))(photos);return {ratingAverage:ratingValues.length?Number((ratingValues.reduce((a,b)=>a+b,0)/ratingValues.length).toFixed(2)):null,ratingCount:ratingValues.length,averageSpend:spends.length?Math.round(spends.reduce((a,b)=>a+b,0)/spends.length):null,spendCount:spends.length,photoCount:new Set(safe).size};}
  function configure(next){storage=next||null;return api;}const api={COOLDOWN_MS,ORDER,configure,detectMissingFields,isCoolingDown,mergeOnlyMissing,enrichPlace,aggregateCommunity,safePhotos};return api;
});
