const { chromium } = require('playwright-core');
const fs = require('fs'); const path = require('path');
const root = path.resolve(__dirname, '..');
const stage = process.env.PERF_STAGE || 'before';
const out = path.join(root, `reports/jia_ben_6_0j_phase2e_performance_${stage}`); fs.mkdirSync(out, { recursive: true });
const url = process.env.PROFILE_URL || 'https://b7516555-max.github.io/jia-ben/';
const vps = [['desktop-1440',1440,900],['mobile-390',390,844],['mobile-320',320,700]];
const chrome = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe';
async function ready(page) { for (let i=0;i<45 && !(await page.locator('.restaurant-card').count());i++) { const b=page.getByText('直接進入網頁版',{exact:false}).first(); if(await b.isVisible().catch(()=>false)) await b.click().catch(()=>{}); await page.waitForTimeout(500); } }
const localFixture = Array.from({length: 5}, (_, i) => ({ jiaPlaceId: `phase2e-${i}`, name: `PHASE2E TEST ${i + 1}`, address: `測試地址 ${i + 1}`, categories: ['測試'], openingHours: '11:00~14:00, 17:00~21:00', coverPhoto: './assets/place-placeholder.svg', location: { lat: 22.67, lng: 120.49 } }));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:chrome}); const results=[]; for(const [name,w,h] of vps){const ctx=await browser.newContext({viewport:{width:w,height:h},serviceWorkers:'block'}),page=await ctx.newPage(); page.setDefaultTimeout(2000); if(stage==='after') await page.addInitScript(()=>{window.__JIA_BEN_ENABLE_PERF=true}); const errors=[]; page.on('pageerror',e=>errors.push(e.message)); await page.goto(`${url}?phase2e=${stage}-${name}`,{waitUntil:'domcontentloaded',timeout:45000}).catch(()=>{}); await ready(page); const cards=page.locator('.restaurant-card'); const count=Math.min(await cards.count(),5); const timings=[]; for(let i=0;i<count;i++){const card=cards.nth(i); await card.scrollIntoViewIfNeeded().catch(()=>{}); const t0=Date.now(); await card.click({position:{x:20,y:20},timeout:2000}).catch(()=>{}); let visible=false; let t3=null; for(let n=0;n<100;n++){visible=await page.locator('#card-detail-modal').evaluate(e=>{const s=getComputedStyle(e);return !e.classList.contains('hidden')&&s.display!=='none'&&s.visibility!=='hidden'&&Number(s.opacity)>0}).catch(()=>false); if(visible){t3=Date.now();break;} await page.waitForTimeout(10)} const instrumentation=await page.evaluate(()=>window.__jiaBenDetailPerf||null); timings.push({index:i,clickToVisibleMs:t3? t3-t0:null,visible,instrumentation}); await page.locator('#card-detail-modal button').first().click({timeout:1000}).catch(()=>{}); await page.keyboard.press('Escape').catch(()=>{}); await page.waitForTimeout(100); } const numeric=await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(e=>{const t=(e.textContent||'').trim();return /\b\d[\d./:-]*\b/.test(t)&&e.children.length===0}).slice(0,80).map(e=>({text:e.textContent.trim().slice(0,80),letterSpacing:getComputedStyle(e).letterSpacing,fontVariant:getComputedStyle(e).fontVariantNumeric}))); results.push({viewport:[w,h],cards:count,timings,numeric,errors}); await ctx.close();} await browser.close(); fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({baseline:stage==='after'?'hotfix-local':'84cf607',results},null,2)); console.log(JSON.stringify(results,null,2));})().catch(e=>{console.error(e.stack||e);process.exitCode=1});
